import { PrismaClient, PlaceCategory, PriceRange } from "@prisma/client";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

const defaultHours = {
  sunday: "09:00 - 22:00",
  monday: "09:00 - 22:00",
  tuesday: "09:00 - 22:00",
  wednesday: "09:00 - 22:00",
  thursday: "09:00 - 23:00",
  friday: "09:00 - 23:00",
  saturday: "10:00 - 23:00",
};

const places = [
  {
    nameHe: "מגדל השעון",
    nameEn: "Clock Tower Square",
    nameAr: "ساحة برج الساعة",
    descriptionHe: "כיכר היסטורית בלב יפו העתיקה, מושלמת לטיול רומנטי בשקיעה.",
    descriptionEn: "Historic square in Old Jaffa, perfect for a romantic sunset stroll.",
    descriptionAr: "ساحة تاريخية في يafa القديمة، مثالية للتنزه الرومانسي عند الغروب.",
    category: PlaceCategory.ROMANTIC_DATE,
    latitude: 32.0543,
    longitude: 34.752,
    address: "שדרות יפת 1, תל אביב-יפו",
    priceRange: PriceRange.FREE,
    images: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800"],
    openingHours: defaultHours,
    displayOrder: 1,
  },
  {
    nameHe: "נמל תל אביב",
    nameEn: "Tel Aviv Port",
    nameAr: "ميناء تل أبيب",
    descriptionHe: "טיילת ים, מסעדות ושקיעות מדהימות על הים התיכון.",
    descriptionEn: "Seaside promenade with restaurants and stunning Mediterranean sunsets.",
    descriptionAr: "ممشى بحري مع مطاعم وغروب رائع على البحر المتوسط.",
    category: PlaceCategory.SUNSET,
    latitude: 32.0975,
    longitude: 34.775,
    address: "נמל תל אביב, תל אביב",
    priceRange: PriceRange.MODERATE,
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800"],
    openingHours: defaultHours,
    displayOrder: 2,
  },
  {
    nameHe: "מסעדת מסה",
    nameEn: "Messa Restaurant",
    nameAr: "مطعم ميسا",
    descriptionHe: "מסעדת שף יוקרתית עם נוף לים, אידיאלית לדייט מיוחד.",
    descriptionEn: "Upscale chef restaurant with sea views, ideal for a special date.",
    descriptionAr: "مطعم شيف فاخر بإطلالة على البحر، مثالي لموعد خاص.",
    category: PlaceCategory.RESTAURANT,
    latitude: 32.0853,
    longitude: 34.7818,
    address: "19 HaArba'a St, Tel Aviv",
    priceRange: PriceRange.EXPENSIVE,
    images: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800"],
    openingHours: defaultHours,
    phone: "03-5174777",
    website: "https://www.messa-rest.co.il",
    deliveryWoltUrl: "https://wolt.com/he/isr/tel-aviv",
    deliveryTenBisUrl: "https://www.tenbis.co.il/",
    deliveryMishlohaUrl: "https://www.mishloha.co.il/",
    displayOrder: 3,
  },
  {
    nameHe: "גן העצמאות",
    nameEn: "Independence Park",
    nameAr: "حديقة الاستقلال",
    descriptionHe: "פארק ירוק על צוק הים, מקום שקט לפיקניק רומנטי.",
    descriptionEn: "Green park on the sea cliff, a quiet spot for a romantic picnic.",
    descriptionAr: "حديقة خضراء على منحدر البحر، مكان هادئ للنزهة الرومانسية.",
    category: PlaceCategory.ROMANTIC_DATE,
    latitude: 32.0912,
    longitude: 34.7695,
    address: "גן העצמאות, תל אביב",
    priceRange: PriceRange.FREE,
    images: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800"],
    openingHours: {
      ...defaultHours,
      sunday: "06:00 - 23:00",
      monday: "06:00 - 23:00",
    },
    displayOrder: 4,
  },
  {
    nameHe: "מוזיאון תל אביב",
    nameEn: "Tel Aviv Museum of Art",
    nameAr: "متحف تل أبيب للفنون",
    descriptionHe: "מוזיאון אמנות מודרנית, דייט תרבותי מעניין.",
    descriptionEn: "Modern art museum for a cultured and interesting date.",
    descriptionAr: "متحف فن حديث لموعد ثقافي وممتع.",
    category: PlaceCategory.ATTRACTION,
    latitude: 32.0773,
    longitude: 34.7861,
    address: "27 Shaul HaMelech Blvd, Tel Aviv",
    priceRange: PriceRange.MODERATE,
    images: ["https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=800"],
    openingHours: {
      sunday: "closed",
      monday: "10:00 - 16:00",
      tuesday: "10:00 - 20:00",
      wednesday: "10:00 - 20:00",
      thursday: "10:00 - 20:00",
      friday: "10:00 - 14:00",
      saturday: "10:00 - 16:00",
    },
    phone: "03-6077020",
    website: "https://www.tamuseum.org.il",
    displayOrder: 5,
  },
  {
    nameHe: "שוק הכרמל",
    nameEn: "Carmel Market",
    nameAr: "سوق الكarmel",
    descriptionHe: "שוק צבעוני עם אוכל רחוב ואווירה תוססת.",
    descriptionEn: "Colorful market with street food and vibrant atmosphere.",
    descriptionAr: "سوق ملون مع طعام الشارع وأجواء حيوية.",
    category: PlaceCategory.ATTRACTION,
    latitude: 32.0667,
    longitude: 34.7692,
    address: "שוק הכרמל, תל אביב",
    priceRange: PriceRange.BUDGET,
    images: ["https://images.unsplash.com/photo-1488459716781-31db71592aa9?w=800"],
    openingHours: {
      sunday: "08:00 - 18:00",
      monday: "08:00 - 18:00",
      tuesday: "08:00 - 18:00",
      wednesday: "08:00 - 18:00",
      thursday: "08:00 - 18:00",
      friday: "08:00 - 15:00",
      saturday: "closed",
    },
    displayOrder: 6,
  },
  {
    nameHe: "חוף גורדון",
    nameEn: "Gordon Beach",
    nameAr: "شاطئ gordon",
    descriptionHe: "חוף פופולרי עם שקיעות מרהיבות ומסעדות על החוף.",
    descriptionEn: "Popular beach with stunning sunsets and beachfront dining.",
    descriptionAr: "شاطئ شهير مع غروب رائع ومطاعم على الشاطئ.",
    category: PlaceCategory.SUNSET,
    latitude: 32.0833,
    longitude: 34.7667,
    address: "חוף גורדון, תל אביב",
    priceRange: PriceRange.FREE,
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"],
    openingHours: defaultHours,
    displayOrder: 7,
  },
  {
    nameHe: "מסעדת עלמה",
    nameEn: "Alma Restaurant",
    nameAr: "مطعم ألما",
    descriptionHe: "מסעדה ים-תיכונית אינטימית בלב העיר.",
    descriptionEn: "Intimate Mediterranean restaurant in the heart of the city.",
    descriptionAr: "مطعم متوسطي حميم في قلب المدينة.",
    category: PlaceCategory.RESTAURANT,
    latitude: 32.0644,
    longitude: 34.7747,
    address: "Alma by the Sea, Tel Aviv",
    priceRange: PriceRange.MODERATE,
    images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800"],
    openingHours: defaultHours,
    displayOrder: 8,
  },
  {
    nameHe: "גשר הולנד",
    nameEn: "Holland Bridge",
    nameAr: "جسر هولندا",
    descriptionHe: "גשר היסטורי ביפו עם נוף פנורמי לים.",
    descriptionEn: "Historic bridge in Jaffa with panoramic sea views.",
    descriptionAr: "جسر تاريخي في يafa بإطلالة بانورامية على البحر.",
    category: PlaceCategory.ROMANTIC_DATE,
    latitude: 32.0519,
    longitude: 34.7514,
    address: "יפו, תל אביב-יפו",
    priceRange: PriceRange.FREE,
    images: ["https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800"],
    openingHours: defaultHours,
    displayOrder: 9,
  },
  {
    nameHe: "מגדל השלום",
    nameEn: "Azrieli Observatory",
    nameAr: "مرصد أزrieli",
    descriptionHe: "תצפית מהמגדלים עם נוף 360 מעלות על תל אביב.",
    descriptionEn: "Tower observatory with 360-degree views of Tel Aviv.",
    descriptionAr: "مرصد في البرج بإطلالة 360 درجة على تل أبيب.",
    category: PlaceCategory.ATTRACTION,
    latitude: 32.074,
    longitude: 34.792,
    address: "Azrieli Center, Tel Aviv",
    priceRange: PriceRange.BUDGET,
    images: ["https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800"],
    openingHours: defaultHours,
    phone: "03-6081010",
    displayOrder: 10,
  },
  {
    nameHe: "מסעדת חלבית ג'афה",
    nameEn: "Jaffa Dairy Kitchen",
    nameAr: "مطبخ يافا الحليبي",
    descriptionHe: "מסעדה חלבית עם פסטות, פיצות ומנות ים תיכוניות — מושלמת לדייט.",
    descriptionEn: "Dairy restaurant with pasta, pizza and Mediterranean dishes — perfect for a date.",
    descriptionAr: "مطعم ألبان مع معكرونة وبيتزا وأطباق متوسطية — مثالي للموعد.",
    category: PlaceCategory.DAIRY_RESTAURANT,
    latitude: 32.062,
    longitude: 34.768,
    address: "שוק הפשפשים, יפו",
    priceRange: PriceRange.MODERATE,
    images: ["https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800"],
    openingHours: defaultHours,
    displayOrder: 11,
  },
  {
    nameHe: "מסעדת הבשרים",
    nameEn: "The Grill House",
    nameAr: "بيت اللحوم",
    descriptionHe: "מסעדה בשרית עם סטייקים, צלעות וגריל — אווירה חמימה ורומנטית.",
    descriptionEn: "Meat restaurant with steaks, ribs and grill — warm romantic atmosphere.",
    descriptionAr: "مطعم لحوم مع ستيكات وأضلاع وشواية — أجواء دافئة ورومانسية.",
    category: PlaceCategory.MEAT_RESTAURANT,
    latitude: 32.078,
    longitude: 34.781,
    address: "רothschild Blvd 45, Tel Aviv",
    priceRange: PriceRange.EXPENSIVE,
    images: ["https://images.unsplash.com/photo-1544025162-d76694265947?w=800"],
    openingHours: defaultHours,
    displayOrder: 12,
  },
  {
    nameHe: "בר סושי תל אביב",
    nameEn: "Tel Aviv Sushi Bar",
    nameAr: "بار سوشي تل أبيب",
    descriptionHe: "בר סושי עם רולים פרימיום, סשימי טרי ואווירה אינטימית.",
    descriptionEn: "Sushi bar with premium rolls, fresh sashimi and an intimate vibe.",
    descriptionAr: "بار سوشي مع لفائف فاخرة وساشimi طازج وأجواء حميمة.",
    category: PlaceCategory.SUSHI,
    latitude: 32.089,
    longitude: 34.776,
    address: "Dizengoff St 112, Tel Aviv",
    priceRange: PriceRange.MODERATE,
    images: ["https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800"],
    openingHours: defaultHours,
    displayOrder: 13,
  },
];

async function main() {
  const adminPasswordHash = await bcrypt.hash("admin123", 12);
  const freePasswordHash = await bcrypt.hash("free123", 12);

  await prisma.user.upsert({
    where: { email: "admin@datespot.co.il" },
    update: {},
    create: {
      fullName: "Admin User",
      age: 30,
      phone: "0500000000",
      email: "admin@datespot.co.il",
      passwordHash: adminPasswordHash,
      subscriptionTier: "VIP",
      isAdmin: true,
    },
  });

  await prisma.user.upsert({
    where: { email: "free@datespot.co.il" },
    update: {
      ageVerifiedAt: new Date(),
      isVisibleNearby: true,
      nearbyLat: 32.086,
      nearbyLng: 34.782,
      nearbyUpdatedAt: new Date(),
    },
    create: {
      fullName: "Free User",
      age: 25,
      phone: "0500000001",
      email: "free@datespot.co.il",
      passwordHash: freePasswordHash,
      subscriptionTier: "FREE",
      isAdmin: false,
      ageVerifiedAt: new Date(),
      isVisibleNearby: true,
      nearbyLat: 32.086,
      nearbyLng: 34.782,
      nearbyUpdatedAt: new Date(),
    },
  });

  for (const place of places) {
    await prisma.place.upsert({
      where: { id: "00000000-0000-0000-0000-" + String(place.displayOrder).padStart(12, "0") },
      update: place,
      create: {
        id: "00000000-0000-0000-0000-" + String(place.displayOrder).padStart(12, "0"),
        ...place,
      },
    });
  }

  console.log(
    "Seed complete: admin@datespot.co.il / admin123, free@datespot.co.il / free123 + 13 Tel Aviv places"
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
